POST http://localhost:8080/api/boards
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="content"

숨 참고
--boundary
Content-Disposition: form-data; name="roadName"

러브
--boundary
Content-Disposition: form-data; name="hashtagNames"
Content-Type: application/json

["다이브, 우우우우"]

--boundary
Content-Disposition: form-data; name="multipartFiles"; filename="test.jpg"
Content-Type: image/gif

test.jpg
--boundary
Content-Disposition: form-data; name="multipartFiles"; filename="6e42d0c6-f5cb-4799-9270-01fe89729b31.png"
Content-Type: image/gif

6e42d0c6-f5cb-4799-9270-01fe89729b31.png
--boundary--

