POST http://localhost:8080/api/boards?memberId=1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="content"

러브
--boundary
Content-Disposition: form-data; name="latitude"

13.5
--boundary
Content-Disposition: form-data; name="longitude"

23.5
--boundary
Content-Disposition: form-data; name="longitude"

23.5
--boundary
Content-Disposition: form-data; name="hashtagNames"
Content-Type: application/json

["구욷, 굳"]
--boundary--
#Content-Disposition: from-data; name="multipartFiles"; filename="test.jpg"
#Content-Type: image/gif
#
#C:\Users\hyeon\OneDrive\Desktop\HappyManwon\src\test\resources\test.jpg
#--boundary

