POST http://localhost:8080/api/boards?memberId=1
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: from-data; name="file"; filename="test.jpg"
Content-Type: image/gif
