spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-k3hsu.pub-cdb.ntruss.com:3306/happymanwon-backend-mysql?characterEncoding=utf8
    username: backend
    password: unhappy123!

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  host: 118.67.134.91
  port: 8080
kakao:
  restApiKey : dceb1b292320a7621e7a4cbbbaf81531
jwt:
  secretKey: happymanwonsecretkeyafterharutalkback3front2pm1when20231211
  accessTokenValidTime: 86400000
  refreshTokenValidTime: 604800000

cloud:
  naver:
    credentials:
      access-key: Qzlhb9RRM7FenseacUZr
      secret-key: Kv1b9A7dRmhcJmFy3PibLF0kymq4oiaxZP9umAvf
    region:
      static: kr-standard
    s3:
      endpoint: https://kr.object.ncloudstorage.com
      bucket: happymanwon-backend

logging:
  level:
    org.apache.coyote.http11.Http11InputBuffer: debug
